-- CollegeRank seed data: Top 50 U.S. Colleges
-- All start at ELO 1500

insert into colleges (name, slug, logo_url, elo_rating, comparisons, wins, losses) values
  ('Harvard University', 'harvard', 'https://upload.wikimedia.org/wikipedia/en/2/29/Harvard_shield_wreath.svg', 1500, 0, 0, 0),
  ('Stanford University', 'stanford', 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Stanford_Cardinal_logo.svg', 1500, 0, 0, 0),
  ('Massachusetts Institute of Technology', 'mit', 'https://upload.wikimedia.org/wikipedia/commons/0/0c/MIT_logo.svg', 1500, 0, 0, 0),
  ('Princeton University', 'princeton', 'https://upload.wikimedia.org/wikipedia/en/7/75/Princeton_shield.svg', 1500, 0, 0, 0),
  ('Yale University', 'yale', 'https://upload.wikimedia.org/wikipedia/en/0/07/Yale_Bulldogs_logo.svg', 1500, 0, 0, 0),
  ('Columbia University', 'columbia', 'https://upload.wikimedia.org/wikipedia/en/9/9b/Columbia_Lions_logo.svg', 1500, 0, 0, 0),
  ('University of Chicago', 'uchicago', 'https://upload.wikimedia.org/wikipedia/en/2/25/UChicago_Maroons_logo.svg', 1500, 0, 0, 0),
  ('University of Pennsylvania', 'upenn', 'https://upload.wikimedia.org/wikipedia/en/9/9e/UPenn_Quakers_logo.svg', 1500, 0, 0, 0),
  ('Duke University', 'duke', 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Duke_Athletics_logo.svg', 1500, 0, 0, 0),
  ('Northwestern University', 'northwestern', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Northwestern_Wildcats_logo.svg', 1500, 0, 0, 0),
  ('Johns Hopkins University', 'johns-hopkins', 'https://upload.wikimedia.org/wikipedia/en/b/b4/Johns_Hopkins_Blue_Jays_logo.svg', 1500, 0, 0, 0),
  ('Dartmouth College', 'dartmouth', 'https://upload.wikimedia.org/wikipedia/en/b/bb/Dartmouth_Big_Green_logo.svg', 1500, 0, 0, 0),
  ('Brown University', 'brown', 'https://upload.wikimedia.org/wikipedia/en/8/84/Brown_Bears_logo.svg', 1500, 0, 0, 0),
  ('Cornell University', 'cornell', 'https://upload.wikimedia.org/wikipedia/en/4/47/Cornell_Big_Red_logo.svg', 1500, 0, 0, 0),
  ('Rice University', 'rice', 'https://upload.wikimedia.org/wikipedia/en/9/9a/Rice_Owls_logo.svg', 1500, 0, 0, 0),
  ('Vanderbilt University', 'vanderbilt', 'https://upload.wikimedia.org/wikipedia/en/7/71/Vanderbilt_Commodores_logo.svg', 1500, 0, 0, 0),
  ('University of Notre Dame', 'notre-dame', 'https://upload.wikimedia.org/wikipedia/en/a/a5/Notre_Dame_Fighting_Irish_logo.svg', 1500, 0, 0, 0),
  ('Georgetown University', 'georgetown', 'https://upload.wikimedia.org/wikipedia/en/7/7e/Georgetown_Hoyas_logo.svg', 1500, 0, 0, 0),
  ('Emory University', 'emory', 'https://upload.wikimedia.org/wikipedia/en/8/8a/Emory_Eagles_logo.svg', 1500, 0, 0, 0),
  ('Washington University in St. Louis', 'washu', 'https://upload.wikimedia.org/wikipedia/en/6/6c/WashU_Bears_logo.svg', 1500, 0, 0, 0),
  ('Tufts University', 'tufts', 'https://upload.wikimedia.org/wikipedia/en/2/2d/Tufts_Jumbos_logo.svg', 1500, 0, 0, 0),
  ('Carnegie Mellon University', 'cmu', 'https://upload.wikimedia.org/wikipedia/en/b/bb/Carnegie_Mellon_Tartans_logo.svg', 1500, 0, 0, 0),
  ('University of California, Berkeley', 'uc-berkeley', 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Cal_Golden_Bears_logo.svg', 1500, 0, 0, 0),
  ('University of California, Los Angeles', 'ucla', 'https://upload.wikimedia.org/wikipedia/commons/0/0d/UCLA_Bruins_logo.svg', 1500, 0, 0, 0),
  ('University of Michigan', 'umich', 'https://upload.wikimedia.org/wikipedia/en/2/21/Michigan_Wolverines_logo.svg', 1500, 0, 0, 0),
  ('University of Virginia', 'uva', 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Virginia_Cavaliers_sabre.svg', 1500, 0, 0, 0),
  ('University of North Carolina at Chapel Hill', 'unc', 'https://upload.wikimedia.org/wikipedia/en/6/6d/North_Carolina_Tar_Heels_logo.svg', 1500, 0, 0, 0),
  ('University of Southern California', 'usc', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/USC_Trojans_logo.svg', 1500, 0, 0, 0),
  ('University of California, San Diego', 'ucsd', 'https://upload.wikimedia.org/wikipedia/en/7/73/UC_San_Diego_Tritons_logo.svg', 1500, 0, 0, 0),
  ('University of California, Davis', 'uc-davis', 'https://upload.wikimedia.org/wikipedia/en/c/c8/UC_Davis_Aggies_logo.svg', 1500, 0, 0, 0),
  ('University of Texas at Austin', 'ut-austin', 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Texas_Longhorns_logo.svg', 1500, 0, 0, 0),
  ('Georgia Institute of Technology', 'gatech', 'https://upload.wikimedia.org/wikipedia/en/8/8d/Georgia_Tech_Yellow_Jackets_logo.svg', 1500, 0, 0, 0),
  ('University of Wisconsin-Madison', 'uw-madison', 'https://upload.wikimedia.org/wikipedia/en/d/d8/Wisconsin_Badgers_logo.svg', 1500, 0, 0, 0),
  ('University of Illinois Urbana-Champaign', 'uiuc', 'https://upload.wikimedia.org/wikipedia/en/5/59/Illinois_Fighting_Illini_logo.svg', 1500, 0, 0, 0),
  ('Purdue University', 'purdue', 'https://upload.wikimedia.org/wikipedia/en/2/23/Purdue_Boilermakers_logo.svg', 1500, 0, 0, 0),
  ('Penn State University', 'penn-state', 'https://upload.wikimedia.org/wikipedia/en/d/d0/Penn_State_Nittany_Lions_logo.svg', 1500, 0, 0, 0),
  ('Ohio State University', 'ohio-state', 'https://upload.wikimedia.org/wikipedia/en/e/e8/Ohio_State_Buckeyes_logo.svg', 1500, 0, 0, 0),
  ('University of Washington', 'uw-seattle', 'https://upload.wikimedia.org/wikipedia/en/b/b8/Washington_Huskies_logo.svg', 1500, 0, 0, 0),
  ('Boston University', 'bu', 'https://upload.wikimedia.org/wikipedia/en/7/72/Boston_University_Terriers_logo.svg', 1500, 0, 0, 0),
  ('Northeastern University', 'northeastern', 'https://upload.wikimedia.org/wikipedia/en/8/89/Northeastern_Huskies_logo.svg', 1500, 0, 0, 0),
  ('Tulane University', 'tulane', 'https://upload.wikimedia.org/wikipedia/en/c/ce/Tulane_Green_Wave_logo.svg', 1500, 0, 0, 0),
  ('Case Western Reserve University', 'case-western', 'https://upload.wikimedia.org/wikipedia/en/9/9b/Case_Western_Reserve_Spartans_logo.svg', 1500, 0, 0, 0),
  ('University of Rochester', 'rochester', 'https://upload.wikimedia.org/wikipedia/en/9/9a/Rochester_Yellowjackets_logo.svg', 1500, 0, 0, 0),
  ('Wake Forest University', 'wake-forest', 'https://upload.wikimedia.org/wikipedia/en/c/c3/Wake_Forest_Demon_Deacons_logo.svg', 1500, 0, 0, 0),
  ('Rensselaer Polytechnic Institute', 'rpi', 'https://upload.wikimedia.org/wikipedia/en/c/c5/RPI_Engineers_logo.svg', 1500, 0, 0, 0),
  ('William & Mary', 'william-and-mary', 'https://upload.wikimedia.org/wikipedia/en/8/8a/William_%26_Mary_Tribe_logo.svg', 1500, 0, 0, 0),
  ('University of Florida', 'uf', 'https://upload.wikimedia.org/wikipedia/en/1/1d/Florida_Gators_logo.svg', 1500, 0, 0, 0),
  ('University of Georgia', 'uga', 'https://upload.wikimedia.org/wikipedia/en/3/3c/Georgia_Bulldogs_logo.svg', 1500, 0, 0, 0),
  ('Indiana University Bloomington', 'indiana', 'https://upload.wikimedia.org/wikipedia/en/9/97/Indiana_Hoosiers_logo.svg', 1500, 0, 0, 0),
  ('University of Minnesota', 'umn', 'https://upload.wikimedia.org/wikipedia/en/1/18/Minnesota_Golden_Gophers_logo.svg', 1500, 0, 0, 0)
on conflict (slug) do nothing;
