/** Maps common country slugs to their emoji flag. */
const FLAG_MAP: Record<string, string> = {
  "united-states": "🇺🇸", usa: "🇺🇸", "us": "🇺🇸", america: "🇺🇸",
  canada: "🇨🇦",
  mexico: "🇲🇽",
  brazil: "🇧🇷",
  argentina: "🇦🇷",
  colombia: "🇨🇴",
  chile: "🇨🇱",
  peru: "🇵🇪",
  venezuela: "🇻🇪",
  ecuador: "🇪🇨",
  uruguay: "🇺🇾",
  paraguay: "🇵🇾",
  bolivia: "🇧🇴",
  "costa-rica": "🇨🇷",
  panama: "🇵🇦",
  cuba: "🇨🇺",
  "dominican-republic": "🇩🇴",
  guatemala: "🇬🇹",
  honduras: "🇭🇳",
  "el-salvador": "🇸🇻",
  nicaragua: "🇳🇮",
  jamaica: "🇯🇲",
  "trinidad-and-tobago": "🇹🇹",
  haiti: "🇭🇹",
  "puerto-rico": "🇵🇷",

  "united-kingdom": "🇬🇧", uk: "🇬🇧", britain: "🇬🇧", england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  france: "🇫🇷",
  germany: "🇩🇪",
  italy: "🇮🇹",
  spain: "🇪🇸",
  portugal: "🇵🇹",
  netherlands: "🇳🇱",
  belgium: "🇧🇪",
  switzerland: "🇨🇭",
  austria: "🇦🇹",
  sweden: "🇸🇪",
  norway: "🇳🇴",
  denmark: "🇩🇰",
  finland: "🇫🇮",
  ireland: "🇮🇪",
  iceland: "🇮🇸",
  poland: "🇵🇱",
  "czech-republic": "🇨🇿", czechia: "🇨🇿",
  romania: "🇷🇴",
  hungary: "🇭🇺",
  greece: "🇬🇷",
  croatia: "🇭🇷",
  serbia: "🇷🇸",
  bulgaria: "🇧🇬",
  slovakia: "🇸🇰",
  slovenia: "🇸🇮",
  ukraine: "🇺🇦",
  russia: "🇷🇺",
  turkey: "🇹🇷",
  luxembourg: "🇱🇺",
  malta: "🇲🇹",
  cyprus: "🇨🇾",
  estonia: "🇪🇪",
  latvia: "🇱🇻",
  lithuania: "🇱🇹",
  albania: "🇦🇱",
  "north-macedonia": "🇲🇰", macedonia: "🇲🇰",
  "bosnia-and-herzegovina": "🇧🇦", bosnia: "🇧🇦",
  montenegro: "🇲🇪",
  kosovo: "🇽🇰",
  moldova: "🇲🇩",
  belarus: "🇧🇾",
  georgia: "🇬🇪",
  armenia: "🇦🇲",
  azerbaijan: "🇦🇿",

  china: "🇨🇳",
  japan: "🇯🇵",
  "south-korea": "🇰🇷", korea: "🇰🇷",
  "north-korea": "🇰🇵",
  india: "🇮🇳",
  indonesia: "🇮🇩",
  thailand: "🇹🇭",
  vietnam: "🇻🇳",
  philippines: "🇵🇭",
  malaysia: "🇲🇾",
  singapore: "🇸🇬",
  taiwan: "🇹🇼",
  "hong-kong": "🇭🇰",
  mongolia: "🇲🇳",
  myanmar: "🇲🇲", burma: "🇲🇲",
  cambodia: "🇰🇭",
  laos: "🇱🇦",
  nepal: "🇳🇵",
  "sri-lanka": "🇱🇰",
  bangladesh: "🇧🇩",
  pakistan: "🇵🇰",
  afghanistan: "🇦🇫",
  iran: "🇮🇷",
  iraq: "🇮🇶",
  "saudi-arabia": "🇸🇦",
  "united-arab-emirates": "🇦🇪", uae: "🇦🇪",
  israel: "🇮🇱",
  jordan: "🇯🇴",
  lebanon: "🇱🇧",
  syria: "🇸🇾",
  qatar: "🇶🇦",
  kuwait: "🇰🇼",
  bahrain: "🇧🇭",
  oman: "🇴🇲",
  yemen: "🇾🇪",
  kazakhstan: "🇰🇿",
  uzbekistan: "🇺🇿",

  australia: "🇦🇺",
  "new-zealand": "🇳🇿",
  fiji: "🇫🇯",

  egypt: "🇪🇬",
  "south-africa": "🇿🇦",
  nigeria: "🇳🇬",
  kenya: "🇰🇪",
  ethiopia: "🇪🇹",
  ghana: "🇬🇭",
  tanzania: "🇹🇿",
  morocco: "🇲🇦",
  algeria: "🇩🇿",
  tunisia: "🇹🇳",
  libya: "🇱🇾",
  uganda: "🇺🇬",
  rwanda: "🇷🇼",
  senegal: "🇸🇳",
  "ivory-coast": "🇨🇮",
  cameroon: "🇨🇲",
  "democratic-republic-of-the-congo": "🇨🇩", congo: "🇨🇩", drc: "🇨🇩",
  madagascar: "🇲🇬",
  mozambique: "🇲🇿",
  zambia: "🇿🇲",
  zimbabwe: "🇿🇼",
  botswana: "🇧🇼",
  namibia: "🇳🇦",
  mauritius: "🇲🇺",
  sudan: "🇸🇩",
  somalia: "🇸🇴",
};

/** Look up a flag emoji for a given slug. Returns null if no match. */
export function getFlag(slug: string): string | null {
  return FLAG_MAP[slug] ?? null;
}
