/** Maps common country slugs to their emoji flag. */
const FLAG_MAP: Record<string, string> = {
  "united-states": "🇺🇸", usa: "🇺🇸", "us": "🇺🇸", america: "🇺🇸", "united-states-of-america": "🇺🇸",
  canada: "🇨🇦",
  mexico: "🇲🇽",
  brazil: "🇧🇷",
  argentina: "🇦🇷",
  colombia: "🇨🇴",
  chile: "🇨🇱",
  peru: "🇵🇪",
  venezuela: "🇻🇪",
  ecuador: "🇪🇨",
  uruguay: "🇺🇾",
  paraguay: "🇵🇾",
  bolivia: "🇧🇴",
  "costa-rica": "🇨🇷",
  panama: "🇵🇦",
  cuba: "🇨🇺",
  "dominican-republic": "🇩🇴",
  guatemala: "🇬🇹",
  honduras: "🇭🇳",
  "el-salvador": "🇸🇻",
  nicaragua: "🇳🇮",
  jamaica: "🇯🇲",
  "trinidad-and-tobago": "🇹🇹",
  haiti: "🇭🇹",
  "puerto-rico": "🇵🇷",
  bahamas: "🇧🇸",
  barbados: "🇧🇧",
  belize: "🇧🇿",
  "antigua-and-barbuda": "🇦🇬",
  dominica: "🇩🇲",
  grenada: "🇬🇩",
  "saint-kitts-and-nevis": "🇰🇳",
  "saint-lucia": "🇱🇨",
  "saint-vincent-and-the-grenadines": "🇻🇨",
  suriname: "🇸🇷",
  guyana: "🇬🇾",

  "united-kingdom": "🇬🇧", uk: "🇬🇧", britain: "🇬🇧", england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  france: "🇫🇷",
  germany: "🇩🇪",
  italy: "🇮🇹",
  spain: "🇪🇸",
  portugal: "🇵🇹",
  netherlands: "🇳🇱",
  belgium: "🇧🇪",
  switzerland: "🇨🇭",
  austria: "🇦🇹",
  sweden: "🇸🇪",
  norway: "🇳🇴",
  denmark: "🇩🇰",
  finland: "🇫🇮",
  ireland: "🇮🇪",
  iceland: "🇮🇸",
  poland: "🇵🇱",
  "czech-republic": "🇨🇿", czechia: "🇨🇿", "czechia-czech-republic": "🇨🇿",
  romania: "🇷🇴",
  hungary: "🇭🇺",
  greece: "🇬🇷",
  croatia: "🇭🇷",
  serbia: "🇷🇸",
  bulgaria: "🇧🇬",
  slovakia: "🇸🇰",
  slovenia: "🇸🇮",
  ukraine: "🇺🇦",
  russia: "🇷🇺",
  turkey: "🇹🇷",
  luxembourg: "🇱🇺",
  malta: "🇲🇹",
  cyprus: "🇨🇾",
  estonia: "🇪🇪",
  latvia: "🇱🇻",
  lithuania: "🇱🇹",
  albania: "🇦🇱",
  "north-macedonia": "🇲🇰", macedonia: "🇲🇰",
  "bosnia-and-herzegovina": "🇧🇦", bosnia: "🇧🇦",
  montenegro: "🇲🇪",
  kosovo: "🇽🇰",
  moldova: "🇲🇩",
  belarus: "🇧🇾",
  georgia: "🇬🇪",
  armenia: "🇦🇲",
  azerbaijan: "🇦🇿",
  liechtenstein: "🇱🇮",
  monaco: "🇲🇨",
  "san-marino": "🇸🇲",
  andorra: "🇦🇩",
  "holy-see": "🇻🇦",
  "eswatini-fmr-swaziland": "🇸🇿", eswatini: "🇸🇿", swaziland: "🇸🇿",

  china: "🇨🇳",
  japan: "🇯🇵",
  "south-korea": "🇰🇷", korea: "🇰🇷",
  "north-korea": "🇰🇵",
  india: "🇮🇳",
  indonesia: "🇮🇩",
  thailand: "🇹🇭",
  vietnam: "🇻🇳",
  philippines: "🇵🇭",
  malaysia: "🇲🇾",
  singapore: "🇸🇬",
  taiwan: "🇹🇼",
  "hong-kong": "🇭🇰",
  mongolia: "🇲🇳",
  myanmar: "🇲🇲", burma: "🇲🇲", "myanmar-formerly-burma": "🇲🇲",
  cambodia: "🇰🇭",
  laos: "🇱🇦",
  nepal: "🇳🇵",
  "sri-lanka": "🇱🇰",
  bangladesh: "🇧🇩",
  pakistan: "🇵🇰",
  afghanistan: "🇦🇫",
  iran: "🇮🇷",
  iraq: "🇮🇶",
  "saudi-arabia": "🇸🇦",
  "united-arab-emirates": "🇦🇪", uae: "🇦🇪",
  israel: "🇮🇱",
  jordan: "🇯🇴",
  lebanon: "🇱🇧",
  syria: "🇸🇾",
  qatar: "🇶🇦",
  kuwait: "🇰🇼",
  bahrain: "🇧🇭",
  oman: "🇴🇲",
  yemen: "🇾🇪",
  kazakhstan: "🇰🇿",
  uzbekistan: "🇺🇿",
  kyrgyzstan: "🇰🇬",
  tajikistan: "🇹🇯",
  turkmenistan: "🇹🇲",
  bhutan: "🇧🇹",
  brunei: "🇧🇳",
  maldives: "🇲🇻",
  "timor-leste": "🇹🇱",
  "palestine-state": "🇵🇸", palestine: "🇵🇸",

  australia: "🇦🇺",
  "new-zealand": "🇳🇿",
  fiji: "🇫🇯",
  "papua-new-guinea": "🇵🇬",
  samoa: "🇼🇸",
  tonga: "🇹🇴",
  vanuatu: "🇻🇺",
  kiribati: "🇰🇮",
  micronesia: "🇫🇲",
  "marshall-islands": "🇲🇭",
  palau: "🇵🇼",
  nauru: "🇳🇷",
  "solomon-islands": "🇸🇧",
  tuvalu: "🇹🇻",

  egypt: "🇪🇬",
  "south-africa": "🇿🇦",
  nigeria: "🇳🇬",
  kenya: "🇰🇪",
  ethiopia: "🇪🇹",
  ghana: "🇬🇭",
  tanzania: "🇹🇿",
  morocco: "🇲🇦",
  algeria: "🇩🇿",
  tunisia: "🇹🇳",
  libya: "🇱🇾",
  uganda: "🇺🇬",
  rwanda: "🇷🇼",
  senegal: "🇸🇳",
  "ivory-coast": "🇨🇮",
  cameroon: "🇨🇲",
  "democratic-republic-of-the-congo": "🇨🇩", congo: "🇨🇩", drc: "🇨🇩",
  "congo-congo-brazzaville": "🇨🇬",
  madagascar: "🇲🇬",
  mozambique: "🇲🇿",
  zambia: "🇿🇲",
  zimbabwe: "🇿🇼",
  botswana: "🇧🇼",
  namibia: "🇳🇦",
  mauritius: "🇲🇺",
  sudan: "🇸🇩",
  somalia: "🇸🇴",
  "south-sudan": "🇸🇸",
  angola: "🇦🇴",
  benin: "🇧🇯",
  "burkina-faso": "🇧🇫",
  burundi: "🇧🇮",
  "cabo-verde": "🇨🇻",
  "central-african-republic": "🇨🇫",
  chad: "🇹🇩",
  comoros: "🇰🇲",
  djibouti: "🇩🇯",
  "equatorial-guinea": "🇬🇶",
  eritrea: "🇪🇷",
  gabon: "🇬🇦",
  gambia: "🇬🇲",
  guinea: "🇬🇳",
  "guinea-bissau": "🇬🇼",
  lesotho: "🇱🇸",
  liberia: "🇱🇷",
  malawi: "🇲🇼",
  mali: "🇲🇱",
  mauritania: "🇲🇷",
  niger: "🇳🇪",
  "sao-tome-and-principe": "🇸🇹",
  seychelles: "🇸🇨",
  "sierra-leone": "🇸🇱",
  togo: "🇹🇬",
};

/** Maps job role slugs to emoji. */
const JOB_MAP: Record<string, string> = {
  actuary: "📊",
  "aerospace-engineer": "🚀",
  architect: "🏛️",
  auditor: "📋",
  "biomedical-engineer": "🧬",
  biostatistician: "🧪",
  "brand-manager": "🏷️",
  "civil-engineer": "🏗️",
  copywriter: "✍️",
  "cyber-security-analyst": "🔐",
  "data-analyst": "📈",
  "data-scientist": "🤖",
  "electrical-engineer": "⚡",
  "environmental-scientist": "🌿",
  "event-planner": "🎉",
  "film-and-video-editor": "🎬",
  "financial-analyst": "💹",
  "full-stack-developer": "💻",
  geologist: "🪨",
  "graphic-designer": "🎨",
  "healthcare-administrator": "🏥",
  "human-resources-specialist": "🤝",
  "industrial-designer": "🔧",
  "interior-designer": "🛋️",
  "investment-banking-analyst": "🏦",
  "management-consultant": "📐",
  "marketing-manager": "📣",
  "mechanical-engineer": "⚙️",
  "occupational-therapist": "🧑‍⚕️",
  "operations-manager": "📦",
  pharmacist: "💊",
  "physical-therapist": "🦴",
  "policy-analyst": "⚖️",
  "product-manager": "🗂️",
  "public-relations-specialist": "📰",
  quant: "🧮",
  "registered-nurse": "🩺",
  "sales-engineer": "🤝",
  "social-worker": "❤️",
  "software-engineer": "👨‍💻",
  "supply-chain-analyst": "🚚",
  teacher: "📚",
  "technical-writer": "📝",
  "urban-planner": "🏙️",
  "uxui-designer": "🖌️",
};

/** Look up an emoji for a given slug. Checks flags and jobs. Returns null if no match. */
export function getFlag(slug: string): string | null {
  return FLAG_MAP[slug] ?? JOB_MAP[slug] ?? null;
}
